apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    turbonomic.io/gitops-source: https://github.com/irfanurrehman/Turbo-ScenarioAsCode
    turbonomic.io/gitops-file-path: changeRequest-test/beekman-orig.yaml
    turbonomic.io/gitops-branch: master
    turbonomic.io/gitops-secret-name: github-credentials
    turbonomic.io/gitops-secret-namespace: default
  name: beekman-change-reconciler
  labels:
    app: bee
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bee
  template:
    metadata:
      labels:
        app: bee
    spec:
      imagePullSecrets:
      - name: docker-credentials
      containers:
      - name: beekman-1
        image: beekman9527/cpumemload:latest
        env:
        - name: RUN_TYPE
          value: "cpu"
        - name: CPU_PERCENT
          value: "100"
        resources:
          requests:
            memory: "100Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "110m"
