apiVersion: v1
kind: Namespace
metadata:
  name: container-up-quota-constraint
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: container-up-quota-constraint
  namespace: container-up-quota-constraint
spec:
  hard:
    limits.cpu: "2000m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cpu-resize-up
  namespace: container-up-quota-constraint
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cpu-resize-up
  template:
    metadata:
      name: cpu-resize-up
      labels:
        app: cpu-resize-up
    spec:
      containers:
        - name: cpu-resize-up
          image: beekman9527/cpumemload:latest
          resources:
            limits:
              cpu: "500m"
            requests:
              cpu: "100m"
          env:
            - name: RUN_TYPE
              value: cpu
            - name: CPU_PERCENT
              value: "100"
